package mymeeting.hibernate.pojo;
// Generated 7-giu-2013 0.23.19 by Hibernate Tools 3.2.1.GA


import com.google.gson.annotations.Expose;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     @Expose
     private String acnId;
     @Expose
     private String acnPasswd;
     @Expose
     private String acnImageUrl;
     @Expose
     private Date acnCreationDate;
     @Expose
     private Boolean flgNeedSync;
     @Expose
     private Date lastUpdate;
     @Expose
     private Boolean flgShowed;
     @Expose
     private Boolean flgDeleted;
     private Set RAcnEvns = new HashSet(0);
     private Set groups = new HashSet(0);
     private Set RAcnGrps = new HashSet(0);
     private Set events = new HashSet(0);
     private Set eventDetts = new HashSet(0);

    public Account() {
    }

	
    public Account(String acnId, String acnPasswd, Date lastUpdate) {
        this.acnId = acnId;
        this.acnPasswd = acnPasswd;
        this.lastUpdate = lastUpdate;
    }
    public Account(String acnId, String acnPasswd, String acnImageUrl, Date acnCreationDate, Boolean flgNeedSync, Date lastUpdate, Boolean flgShowed, Boolean flgDeleted, Set RAcnEvns, Set groups, Set RAcnGrps, Set events, Set eventDetts) {
       this.acnId = acnId;
       this.acnPasswd = acnPasswd;
       this.acnImageUrl = acnImageUrl;
       this.acnCreationDate = acnCreationDate;
       this.flgNeedSync = flgNeedSync;
       this.lastUpdate = lastUpdate;
       this.flgShowed = flgShowed;
       this.flgDeleted = flgDeleted;
       this.RAcnEvns = RAcnEvns;
       this.groups = groups;
       this.RAcnGrps = RAcnGrps;
       this.events = events;
       this.eventDetts = eventDetts;
    }
   
    public String getAcnId() {
        return this.acnId;
    }
    
    public void setAcnId(String acnId) {
        this.acnId = acnId;
    }
    public String getAcnPasswd() {
        return this.acnPasswd;
    }
    
    public void setAcnPasswd(String acnPasswd) {
        this.acnPasswd = acnPasswd;
    }
    public String getAcnImageUrl() {
        return this.acnImageUrl;
    }
    
    public void setAcnImageUrl(String acnImageUrl) {
        this.acnImageUrl = acnImageUrl;
    }
    public Date getAcnCreationDate() {
        return this.acnCreationDate;
    }
    
    public void setAcnCreationDate(Date acnCreationDate) {
        this.acnCreationDate = acnCreationDate;
    }
    public Boolean getFlgNeedSync() {
        return this.flgNeedSync;
    }
    
    public void setFlgNeedSync(Boolean flgNeedSync) {
        this.flgNeedSync = flgNeedSync;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    public Boolean getFlgShowed() {
        return this.flgShowed;
    }
    
    public void setFlgShowed(Boolean flgShowed) {
        this.flgShowed = flgShowed;
    }
    public Boolean getFlgDeleted() {
        return this.flgDeleted;
    }
    
    public void setFlgDeleted(Boolean flgDeleted) {
        this.flgDeleted = flgDeleted;
    }
    public Set getRAcnEvns() {
        return this.RAcnEvns;
    }
    
    public void setRAcnEvns(Set RAcnEvns) {
        this.RAcnEvns = RAcnEvns;
    }
    public Set getGroups() {
        return this.groups;
    }
    
    public void setGroups(Set groups) {
        this.groups = groups;
    }
    public Set getRAcnGrps() {
        return this.RAcnGrps;
    }
    
    public void setRAcnGrps(Set RAcnGrps) {
        this.RAcnGrps = RAcnGrps;
    }
    public Set getEvents() {
        return this.events;
    }
    
    public void setEvents(Set events) {
        this.events = events;
    }
    public Set getEventDetts() {
        return this.eventDetts;
    }
    
    public void setEventDetts(Set eventDetts) {
        this.eventDetts = eventDetts;
    }




}


