package mymeeting.hibernate.pojo;
// Generated 7-giu-2013 0.23.19 by Hibernate Tools 3.2.1.GA


import com.google.gson.annotations.Expose;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Event generated by hbm2java
 */
public class Event  implements java.io.Serializable {


     @Expose
     private String evnId;
     private Group group;
     private Account account;
     @Expose
     private String evnDescription;
     @Expose
     private String evnImageUrl;
     @Expose
     private Date evnDate;
     @Expose
     private Date evnCreationDate;
     @Expose
     private Boolean flgNeedSync;
     @Expose
     private Date lastUpdate;
     @Expose
     private Boolean flgShowed;
     @Expose
     private Boolean flgDeleted;
     private Set eventDetts = new HashSet(0);
     private Set RAcnEvns = new HashSet(0);

    public Event() {
    }

	
    public Event(String evnId, Date lastUpdate) {
        this.evnId = evnId;
        this.lastUpdate = lastUpdate;
    }
    public Event(String evnId, Group group, Account account, String evnDescription, String evnImageUrl, Date evnDate, Date evnCreationDate, Boolean flgNeedSync, Date lastUpdate, Boolean flgShowed, Boolean flgDeleted, Set eventDetts, Set RAcnEvns) {
       this.evnId = evnId;
       this.group = group;
       this.account = account;
       this.evnDescription = evnDescription;
       this.evnImageUrl = evnImageUrl;
       this.evnDate = evnDate;
       this.evnCreationDate = evnCreationDate;
       this.flgNeedSync = flgNeedSync;
       this.lastUpdate = lastUpdate;
       this.flgShowed = flgShowed;
       this.flgDeleted = flgDeleted;
       this.eventDetts = eventDetts;
       this.RAcnEvns = RAcnEvns;
    }
   
    public String getEvnId() {
        return this.evnId;
    }
    
    public void setEvnId(String evnId) {
        this.evnId = evnId;
    }
    public Group getGroup() {
        return this.group;
    }
    
    public void setGroup(Group group) {
        this.group = group;
    }
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    public String getEvnDescription() {
        return this.evnDescription;
    }
    
    public void setEvnDescription(String evnDescription) {
        this.evnDescription = evnDescription;
    }
    public String getEvnImageUrl() {
        return this.evnImageUrl;
    }
    
    public void setEvnImageUrl(String evnImageUrl) {
        this.evnImageUrl = evnImageUrl;
    }
    public Date getEvnDate() {
        return this.evnDate;
    }
    
    public void setEvnDate(Date evnDate) {
        this.evnDate = evnDate;
    }
    public Date getEvnCreationDate() {
        return this.evnCreationDate;
    }
    
    public void setEvnCreationDate(Date evnCreationDate) {
        this.evnCreationDate = evnCreationDate;
    }
    public Boolean getFlgNeedSync() {
        return this.flgNeedSync;
    }
    
    public void setFlgNeedSync(Boolean flgNeedSync) {
        this.flgNeedSync = flgNeedSync;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    public Boolean getFlgShowed() {
        return this.flgShowed;
    }
    
    public void setFlgShowed(Boolean flgShowed) {
        this.flgShowed = flgShowed;
    }
    public Boolean getFlgDeleted() {
        return this.flgDeleted;
    }
    
    public void setFlgDeleted(Boolean flgDeleted) {
        this.flgDeleted = flgDeleted;
    }
    public Set getEventDetts() {
        return this.eventDetts;
    }
    
    public void setEventDetts(Set eventDetts) {
        this.eventDetts = eventDetts;
    }
    public Set getRAcnEvns() {
        return this.RAcnEvns;
    }
    
    public void setRAcnEvns(Set RAcnEvns) {
        this.RAcnEvns = RAcnEvns;
    }




}


