package mymeeting.hibernate.pojo;
// Generated 7-giu-2013 0.23.19 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * RAcnGrp generated by hbm2java
 */
public class RAcnGrp  implements java.io.Serializable {


     private RAcnGrpId id;
     private Group group;
     private Account account;
     private Date acngrpCreationDate;
     private Boolean acngrpConfirmed;
     private Boolean flgNeedSync;
     private Date lastUpdate;
     private Boolean flgShowed;
     private Boolean flgDeleted;

    public RAcnGrp() {
    }

	
    public RAcnGrp(RAcnGrpId id, Group group, Account account, Date lastUpdate) {
        this.id = id;
        this.group = group;
        this.account = account;
        this.lastUpdate = lastUpdate;
    }
    public RAcnGrp(RAcnGrpId id, Group group, Account account, Date acngrpCreationDate, Boolean acngrpConfirmed, Boolean flgNeedSync, Date lastUpdate, Boolean flgShowed, Boolean flgDeleted) {
       this.id = id;
       this.group = group;
       this.account = account;
       this.acngrpCreationDate = acngrpCreationDate;
       this.acngrpConfirmed = acngrpConfirmed;
       this.flgNeedSync = flgNeedSync;
       this.lastUpdate = lastUpdate;
       this.flgShowed = flgShowed;
       this.flgDeleted = flgDeleted;
    }
   
    public RAcnGrpId getId() {
        return this.id;
    }
    
    public void setId(RAcnGrpId id) {
        this.id = id;
    }
    public Group getGroup() {
        return this.group;
    }
    
    public void setGroup(Group group) {
        this.group = group;
    }
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    public Date getAcngrpCreationDate() {
        return this.acngrpCreationDate;
    }
    
    public void setAcngrpCreationDate(Date acngrpCreationDate) {
        this.acngrpCreationDate = acngrpCreationDate;
    }
    public Boolean getAcngrpConfirmed() {
        return this.acngrpConfirmed;
    }
    
    public void setAcngrpConfirmed(Boolean acngrpConfirmed) {
        this.acngrpConfirmed = acngrpConfirmed;
    }
    public Boolean getFlgNeedSync() {
        return this.flgNeedSync;
    }
    
    public void setFlgNeedSync(Boolean flgNeedSync) {
        this.flgNeedSync = flgNeedSync;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    public Boolean getFlgShowed() {
        return this.flgShowed;
    }
    
    public void setFlgShowed(Boolean flgShowed) {
        this.flgShowed = flgShowed;
    }
    public Boolean getFlgDeleted() {
        return this.flgDeleted;
    }
    
    public void setFlgDeleted(Boolean flgDeleted) {
        this.flgDeleted = flgDeleted;
    }
                           
}
