package it.marberpp.myevents.hibernate.pojo;
// Generated 19-mag-2013 15.00.25 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.google.gson.annotations.Expose;

/**
 * Event generated by hbm2java
 */
public class Event  implements java.io.Serializable {

	@Expose
     private String evnId;
	@Expose
     private Group group;
	@Expose
     private String evnDescription;
	@Expose
     private String evnImageUrl;
	@Expose
     private Date evnDate;
	@Expose
     private Date evnCreationDate;
     private Set<EventDett> eventDetts = new HashSet<EventDett>(0);
     private Set<RAcnEvn> RAcnEvns = new HashSet<RAcnEvn>(0);

    public Event() {
    }

	
    public Event(String evnId) {
        this.evnId = evnId;
    }
    public Event(String evnId, Group group, String evnDescription, String evnImageUrl, Date evnDate, Date evnCreationDate, Set<EventDett> eventDetts, Set<RAcnEvn> RAcnEvns) {
       this.evnId = evnId;
       this.group = group;
       this.evnDescription = evnDescription;
       this.evnImageUrl = evnImageUrl;
       this.evnDate = evnDate;
       this.evnCreationDate = evnCreationDate;
       this.eventDetts = eventDetts;
       this.RAcnEvns = RAcnEvns;
    }
   
    public String getEvnId() {
        return this.evnId;
    }
    
    public void setEvnId(String evnId) {
        this.evnId = evnId;
    }
    public Group getGroup() {
        return this.group;
    }
    
    public void setGroup(Group group) {
        this.group = group;
    }
    public String getEvnDescription() {
        return this.evnDescription;
    }
    
    public void setEvnDescription(String evnDescription) {
        this.evnDescription = evnDescription;
    }
    public String getEvnImageUrl() {
        return this.evnImageUrl;
    }
    
    public void setEvnImageUrl(String evnImageUrl) {
        this.evnImageUrl = evnImageUrl;
    }
    public Date getEvnDate() {
        return this.evnDate;
    }
    
    public void setEvnDate(Date evnDate) {
        this.evnDate = evnDate;
    }
    public Date getEvnCreationDate() {
        return this.evnCreationDate;
    }
    
    public void setEvnCreationDate(Date evnCreationDate) {
        this.evnCreationDate = evnCreationDate;
    }
    public Set<EventDett> getEventDetts() {
        return this.eventDetts;
    }
    
    public void setEventDetts(Set<EventDett> eventDetts) {
        this.eventDetts = eventDetts;
    }
    public Set<RAcnEvn> getRAcnEvns() {
        return this.RAcnEvns;
    }
    
    public void setRAcnEvns(Set<RAcnEvn> RAcnEvns) {
        this.RAcnEvns = RAcnEvns;
    }




}


