package it.marberpp.myevents.hibernate.pojo;
// Generated 19-mag-2013 15.00.25 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Group generated by hbm2java
 */
public class Group  implements java.io.Serializable {


     private String grpId;
     private Account account;
     private String grpDescription;
     private String grpImageUrl;
     private Date grpCreationDate;
     private Set<Event> events = new HashSet<Event>(0);
     private Set<RAcnGrp> RAcnGrps = new HashSet<RAcnGrp>(0);

    public Group() {
    }

	
    public Group(String grpId, Account account, Date grpCreationDate) {
        this.grpId = grpId;
        this.account = account;
        this.grpCreationDate = grpCreationDate;
    }
    public Group(String grpId, Account account, String grpDescription, String grpImageUrl, Date grpCreationDate, Set<Event> events, Set<RAcnGrp> RAcnGrps) {
       this.grpId = grpId;
       this.account = account;
       this.grpDescription = grpDescription;
       this.grpImageUrl = grpImageUrl;
       this.grpCreationDate = grpCreationDate;
       this.events = events;
       this.RAcnGrps = RAcnGrps;
    }
   
    public String getGrpId() {
        return this.grpId;
    }
    
    public void setGrpId(String grpId) {
        this.grpId = grpId;
    }
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    public String getGrpDescription() {
        return this.grpDescription;
    }
    
    public void setGrpDescription(String grpDescription) {
        this.grpDescription = grpDescription;
    }
    public String getGrpImageUrl() {
        return this.grpImageUrl;
    }
    
    public void setGrpImageUrl(String grpImageUrl) {
        this.grpImageUrl = grpImageUrl;
    }
    public Date getGrpCreationDate() {
        return this.grpCreationDate;
    }
    
    public void setGrpCreationDate(Date grpCreationDate) {
        this.grpCreationDate = grpCreationDate;
    }
    public Set<Event> getEvents() {
        return this.events;
    }
    
    public void setEvents(Set<Event> events) {
        this.events = events;
    }
    public Set<RAcnGrp> getRAcnGrps() {
        return this.RAcnGrps;
    }
    
    public void setRAcnGrps(Set<RAcnGrp> RAcnGrps) {
        this.RAcnGrps = RAcnGrps;
    }




}


