package it.marberpp.myevents.hibernate.pojo;
// Generated 19-mag-2013 15.00.25 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * RAcnGrp generated by hbm2java
 */
public class RAcnGrp  implements java.io.Serializable {


     private RAcnGrpId id;
     private Group group;
     private Account account;
     private Date acngrpCreationDate;
     private Boolean acngrpConfirmed;

    public RAcnGrp() {
    }

	
    public RAcnGrp(RAcnGrpId id, Group group, Account account) {
        this.id = id;
        this.group = group;
        this.account = account;
    }
    public RAcnGrp(RAcnGrpId id, Group group, Account account, Date acngrpCreationDate, Boolean acngrpConfirmed) {
       this.id = id;
       this.group = group;
       this.account = account;
       this.acngrpCreationDate = acngrpCreationDate;
       this.acngrpConfirmed = acngrpConfirmed;
    }
   
    public RAcnGrpId getId() {
        return this.id;
    }
    
    public void setId(RAcnGrpId id) {
        this.id = id;
    }
    public Group getGroup() {
        return this.group;
    }
    
    public void setGroup(Group group) {
        this.group = group;
    }
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    public Date getAcngrpCreationDate() {
        return this.acngrpCreationDate;
    }
    
    public void setAcngrpCreationDate(Date acngrpCreationDate) {
        this.acngrpCreationDate = acngrpCreationDate;
    }
    public Boolean getAcngrpConfirmed() {
        return this.acngrpConfirmed;
    }
    
    public void setAcngrpConfirmed(Boolean acngrpConfirmed) {
        this.acngrpConfirmed = acngrpConfirmed;
    }




}


