package it.marberpp.myevents.hibernate.pojo;
// Generated 19-mag-2013 15.00.25 by Hibernate Tools 3.2.1.GA



/**
 * RAcnGrpId generated by hbm2java
 */
public class RAcnGrpId  implements java.io.Serializable {


     private String acnId;
     private String grpId;

    public RAcnGrpId() {
    }

    public RAcnGrpId(String acnId, String grpId) {
       this.acnId = acnId;
       this.grpId = grpId;
    }
   
    public String getAcnId() {
        return this.acnId;
    }
    
    public void setAcnId(String acnId) {
        this.acnId = acnId;
    }
    public String getGrpId() {
        return this.grpId;
    }
    
    public void setGrpId(String grpId) {
        this.grpId = grpId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RAcnGrpId) ) return false;
		 RAcnGrpId castOther = ( RAcnGrpId ) other; 
         
		 return ( (this.getAcnId()==castOther.getAcnId()) || ( this.getAcnId()!=null && castOther.getAcnId()!=null && this.getAcnId().equals(castOther.getAcnId()) ) )
 && ( (this.getGrpId()==castOther.getGrpId()) || ( this.getGrpId()!=null && castOther.getGrpId()!=null && this.getGrpId().equals(castOther.getGrpId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getAcnId() == null ? 0 : this.getAcnId().hashCode() );
         result = 37 * result + ( getGrpId() == null ? 0 : this.getGrpId().hashCode() );
         return result;
   }   


}


