package it.marberpp.myevents.hibernate.pojo;
// Generated 19-mag-2013 15.00.25 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * RAcnEvn generated by hbm2java
 */
public class RAcnEvn  implements java.io.Serializable {


     private RAcnEvnId id;
     private Event event;
     private Account account;
     private Boolean acnevnConfirmed;
     private Date acnevnConfirmationDate;

    public RAcnEvn() {
    }

	
    public RAcnEvn(RAcnEvnId id, Event event, Account account) {
        this.id = id;
        this.event = event;
        this.account = account;
    }
    public RAcnEvn(RAcnEvnId id, Event event, Account account, Boolean acnevnConfirmed, Date acnevnConfirmationDate) {
       this.id = id;
       this.event = event;
       this.account = account;
       this.acnevnConfirmed = acnevnConfirmed;
       this.acnevnConfirmationDate = acnevnConfirmationDate;
    }
   
    public RAcnEvnId getId() {
        return this.id;
    }
    
    public void setId(RAcnEvnId id) {
        this.id = id;
    }
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    public Boolean getAcnevnConfirmed() {
        return this.acnevnConfirmed;
    }
    
    public void setAcnevnConfirmed(Boolean acnevnConfirmed) {
        this.acnevnConfirmed = acnevnConfirmed;
    }
    public Date getAcnevnConfirmationDate() {
        return this.acnevnConfirmationDate;
    }
    
    public void setAcnevnConfirmationDate(Date acnevnConfirmationDate) {
        this.acnevnConfirmationDate = acnevnConfirmationDate;
    }




}


